categoryFolderPath = "C:/Users/NikolaKarpic/Desktop/karpaproject/kategorije/"
documentFolderPath = "C:/Users/NikolaKarpic/Desktop/karpaproject/dokumenti/"
contentFolderPath = "C:/Users/NikolaKarpic/Desktop/karpaproject/sadrzaj/"
desktopPath = "C:/Users/NikolaKarpic/Desktop/"
printDoc = "C:/Users/NikolaKarpic/Desktop/karpaproject/dokumenti/2018-10-10 000003 CK102-09 IzvodIzKatastra.pdf.pdf"
HTMLDocPath = 'documents/homepage.html'
popplerPath = 'C:/Users/NikolaKarpic/Desktop/karpaproject/poppler-0.68.0/bin/'
tessereactPath = "C:/Program Files/Tesseract-OCR/tesseract.exe"
calculateContent = 'True'